add Installed-Size field
hwittenborn/makedeb pull request #264
Opened 2023-04-12 20:20 UTC by huakim

modified:   main.sh

2023-04-23 00:43 UTC, Henryws requested changes

2023-04-23 00:43 UTC, Henryws commented on src/main.sh
> +    then
```suggestion
    if [[ -d ${pkgdir} ]]; then
```

2023-04-23 00:43 UTC, Henryws commented on src/main.sh
> +	fi
```suggestion
    fi
```

2023-05-02 19:45 UTC, huakim commented
.

2023-05-02 19:45 UTC, closed without merging

2023-05-02 20:00 UTC, Henryws commented
🤨

2023-05-02 22:13 UTC, hwittenborn commented
@huakim: Is something wrong? Is it because of the long review time or something else? If it's just because I haven't gotten to reviewing this yet, I've just been terribly busy lately working on other projects that have been taking up a ton of my time.

Is it that, or is something else going on?