Add bash completions
hwittenborn/makedeb pull request #44
Opened 2021-10-16 20:35 UTC by Henryws

When you run makedeb as root, it fails, so simply creating a user will make makedeb work in Docker

Also the indentations are messed up on the completions, idk why

Fixes #43

2021-10-16 22:16 UTC, gamer4life1 commented
`sudo` isn't a user iirc, it's a group? :P

2021-10-16 22:17 UTC, Henryws commented
Yup, it's a group. It's wheel on arch systems

2021-10-16 22:22 UTC, gamer4life1 commented
can you use adduser to add a group?

2021-10-16 22:32 UTC, Henryws commented
not that I know of

2021-10-17 02:36 UTC, lpuv commented on docker/Dockerfile
> +RUN adduser makedeb sudo
uh... this is what I meant

2021-10-17 03:52 UTC, hwittenborn commented
Docker images are actually currently handled in the makedeb/makedeb-docker repository :P. That's my bad for not removing the docker/ folder, I'll try to get that done soon.

If you head over to that repository, the makedeb user is also already implemented for everything, so that should all be covered unless there was something else you were looking at adding.

The Bash completions look promising though! I'll give those a spin and let you know how that part goes. For the time being you can go ahead and just delete the docker/ folder too, as there's no plan to keep it.

2021-11-18 01:09 UTC, hwittenborn requested changes
Could you remove the `src/dependency_deb/` files? I don't see any reason why they would be needed.

2021-12-04 04:00 UTC, hwittenborn submitted a review, later dismissed

2021-12-04 04:00 UTC, hwittenborn commented on src/completions/bash
> +			COMPREPLY=( $( compgen -W "$(\ls -1aA .)" -- $cur ) )
This doesn't appear to be working on files that contain spaces (i.e. `hello world.txt`). Maybe something like this?

```sh
mapfile -t COMPREPLY < <(ls -1aA | grep "^${cur}" 2> /dev/null)
```

This has the downside that the user can't specify files that contain any regex, but I think this method would cover more common file names.

2021-12-04 04:00 UTC, hwittenborn commented on src/completions/bash
> +	esac
Why not have this at the bottom of the previous `case` statement?

2021-12-04 04:00 UTC, hwittenborn commented on src/completions/bash
> +} &&
Why are we using `&&` (or anything in general) here?

2021-12-04 04:00 UTC, hwittenborn commented on src/completions/bash
> +			;;
I'd prefer these be listed as just arrays:

```sh

		-*)
			COMPREPLY=('--ignore-arch' '--no-deps' '--file' '--gen-integ'
                                   '--help' '--field' '--install' '--version'
                                   '--rm-deps' '--sync-deps' '--print-control' '--print-srcinfo'
                                   '--skip-pgp-check' '--verbose' '--as-deps' '--no-confirm')
			;;

		*)
			COMPREPLY=('-A' '-d' '-F' '-g' '-h' '-H' '-i' '-V' '-r' '-s')
			;;
```

`-i`, `--install`, and `--as-deps` are also not available on the Arch Linux releases, though that'll require some changes in the Makefile that I can just deal with after merging.

2021-12-05 14:24 UTC, Henryws commented on src/completions/bash
> +			COMPREPLY=( $( compgen -W "$(\ls -1aA .)" -- $cur ) )
Well, the problem with mapfile is that it doesn't exist in zsh, which is useful becaues zsh can emulate bash completions, with the exception of mapfile

2021-12-11 06:37 UTC, hwittenborn approved these changes
Woop woop woop

2021-12-11 06:39 UTC, hwittenborn approved these changes
Yep yep yep yep yep

2021-12-11 06:40 UTC, merged