fix: prevent pkgname or pkgbase from having capital letters
hwittenborn/makedeb pull request #96
Opened 2022-01-01 23:55 UTC by Henryws

Fixes #78

2022-01-02 00:13 UTC, hwittenborn requested changes

2022-01-02 00:13 UTC, hwittenborn commented on src/makedeb/main.sh
> +
This should be placed in `src/makepkg/functions/lint_pkgbuild/pkgname.sh`, as well any future linting checks.

I think there's some still in makedeb's code, but I'm wanting them to stay in makepkg if at all possible.

2022-01-04 15:32 UTC, gamer4life1 approved these changes
LGTM

2022-01-09 11:38 UTC, hwittenborn requested changes

2022-01-09 11:38 UTC, hwittenborn commented on src/makepkg/functions/lint_pkgbuild/pkgbase.sh
> +	fi
Can you add a newline above this `if` statement?

2022-01-09 11:41 UTC, hwittenborn requested changes

2022-01-09 11:41 UTC, hwittenborn commented on src/makepkg/functions/lint_pkgbuild/pkgname.sh
> +	fi
This and the other change in `pkgbase.sh` can both just put in `lint_one_pkgname`, right?

2022-01-09 22:17 UTC, hwittenborn requested changes

2022-01-09 22:17 UTC, hwittenborn commented on src/makepkg/functions/lint_pkgbuild/pkgname.sh
> +
This should be the last thing, but you could be able to put these under one `if` statement but just checking the `${type}` and `${name}` variables as with the statements above it.

2022-01-17 02:48 UTC, hwittenborn commented
Can you merge in the upstream changes? It should fix that downgrading issue that appears during unit tests.

2022-01-18 01:00 UTC, hwittenborn approved these changes

2022-01-18 07:24 UTC, hwittenborn approved these changes
A-OK to me

2022-01-18 15:30 UTC, gamer4life1 approved these changes
LGTM

2022-01-18 15:43 UTC, merged